image: php:7.4-fpm

cache:
  key: one-key-to-rule-them-all
  paths:
    - vendor/
    - node_modules/

before_script:
  - apt-get update
  - apt-get install -y git libzip-dev libpng-dev
  - docker-php-ext-install zip
  - curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$KNOWN_HOSTS" >> ~/.ssh/known_hosts
  - echo "$SSH_KEY" >> ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-add -l
  - echo "$SSH_CONFIG" >> ~/.ssh/config
  - git remote set-url --push origin ssh://git@255.255.255.255:65535/web/sample_project.git
  - git remote -v
  - git remote update
  - git config --global user.name gitlab_runner
  - git config --global user.email gitlab.runner@example.com
  - if [[ `git branch | grep $CI_COMMIT_REF_NAME` ]]; then 
  -   git branch -D $CI_COMMIT_REF_NAME
  - fi
  - if [[ ! `git branch | grep $CI_COMMIT_REF_NAME` ]]; then 
  -   git branch $CI_COMMIT_REF_NAME origin/$CI_COMMIT_REF_NAME
  - fi
  - git branch

stages:
  - build
  - formatter

formatter:
  stage: formatter
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - apt-get install -y lsof nodejs npm
    - npm install
    - pecl install mongodb
    - docker-php-ext-enable mongodb
    - git checkout $CI_COMMIT_REF_NAME
    - ssh -t -t web_app_db -f -N
    - lsof -i
    - composer install
    - cp .env.example .env
    - echo "$ENV_FILE" >> .env
    - php artisan key:generate
    - vendor/bin/phpunit tests/Feature/api_test.php
    - vendor/bin/phpunit tests/Feature/Api
    - SYNTAX_CHECK=0
    - for FILE in `git diff --name-only origin/master | grep -E '*php'` ; do
    - echo $FILE
    - ./vendor/bin/php-cs-fixer fix $FILE
    - echo 'PHPMDで未使用変数などのチェック'
    - if ! ./vendor/bin/phpmd $FILE text ruleset.xml; then
    -   SYNTAX_CHECK=1
    - fi
    - done
    - IS_ERROR=0
    - for FILE in `git diff --name-only origin/master | grep -E '*js'` ; do
    - if [ $FILE = '.eslintrc.json' ]; then
    -   echo $FILE
    -   echo "skip check"
    -   continue
    - fi
    - if [ $FILE = 'composer.json' ]; then
    -   echo $FILE
    -   echo "skip check"
    -   continue
    - fi
    - if [ $FILE = 'package-lock.json' ]; then
    -   echo $FILE
    -   echo "skip check"
    -   continue
    - fi
    - if [ $FILE = 'package.json' ]; then
    -   echo $FILE
    -   echo "skip check"
    -   continue
    - fi
    - if [ $FILE = WebGL_Release.framework.js ]; then
    -   echo $FILE
    -   echo "skip check"
    -   continue
    - fi
    - if [[ -n `./node_modules/.bin/eslint --fix $FILE` ]]; then
    -   ./node_modules/.bin/eslint --fix $FILE
    -   IS_ERROR=1
    - fi
    - done
    - git add -A
    - git status
    - if [[ -n "`git status --porcelain`" ]];then
    - git commit -m '[ci skip]Push by GitLab runner'
    - git push origin $CI_COMMIT_REF_NAME
    - fi
    - IS_ERROR_LOG_REMAIN_ERROR=0
    - for FILE in `git diff --name-only origin/master | grep -E '*php'`; do
    - echo $FILE
    - if [[ -n `git grep error_log -- $FILE` ]]; then
    -   echo -e "\e[31;43m デバッグコードが残っている可能性があります。'\n'削除してください \e[m"
    -   IS_ERROR_LOG_REMAIN_ERROR=1
    - else
    -   IS_ERROR_LOG_REMAIN_ERROR=0
    - fi

    - done
    - if [ $SYNTAX_CHECK -eq 0 -a $IS_ERROR_LOG_REMAIN_ERROR -eq 0 ]; then
    - exit 0
    - else
    - echo -e "\e[31;43m 修正を行った上で再度コミットしてください \e[m"
    - exit 1
    - fi
  except:
    - master
