image: php:7.3-fpm

cache:
  key: one-key-to-rule-them-all
  paths:
    - vendor/
    - node_modules/

before_script:
  - apt-get update
  - apt-get install -y git libzip-dev
  - docker-php-ext-install zip
  - curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$KNOWN_HOSTS" >> ~/.ssh/known_hosts
  - echo "$SSH_KEY" >> ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-add -l
  - git branch
  - git config --global user.name nagaitakuya
  - git config --global user.email nagai.takuya@cimx-initiative.com


stages:
  - build
  - formatter
  - deploy

formatter:
  stage: formatter
  script:
    - apt-get install -y nodejs npm
    - npm install -g prettier
    - git checkout $CI_COMMIT_REF_NAME
    - composer install
    # - cp .env.example .env
    # - php artisan key:generate
    # - vendor/bin/phpunit
    - SYNTAX_CHECK=0
    - for FILE in `git diff --name-only feature/cimx-seat $CI_COMMIT_REF_NAME | grep .php` ; do 
    - echo $FILE
    - ./vendor/bin/php-cs-fixer fix $FILE
    - echo 'PHPMDで未使用変数などのチェック'
    - if ! ./vendor/bin/phpmd $FILE text ruleset.xml; then
    -   SYNTAX_CHECK=1
    - fi
    - done
    - IS_ERROR=0
    - for FILE in `git diff --name-only feature/cimx-seat $CI_COMMIT_REF_NAME | grep .js` ; do
    - err=$(./node_modules/.bin/eslint --fix $FILE)
    - if [ "$err" != '' ]; then
    -   ./node_modules/.bin/eslint --fix $FILE
    -   IS_ERROR=1
    - fi
    - done
    - git add -A
    - git status
    - if [[ -n "`git status --porcelain`" ]];then
    - git commit -m '[ci skip]Push by GitLab runner'
    - git push origin $CI_COMMIT_REF_NAME
    - fi
    - IS_ERROR_LOG_REMAIN_ERROR=0
    - IS_LOG_REMAIN_ERROR=0
    - for FILE in `git diff --name-only $CI_MERGE_REQUEST_TARGET_BRANCH_NAME $CI_COMMIT_REF_NAME | grep .php`; do
    -   error_log_check=$(git grep error_log -- $FILE)
    -   if [[ -n ${error_log_check} ]]; then
    -     echo -e "\e[31;43m デバッグコードが残っている可能性があります。'\n'削除してください \e[m"
    -     IS_ERROR_LOG_REMAIN_ERROR=1
    -   else
    -     IS_ERROR_LOG_REMAIN_ERROR=0
    -   fi
    -   log_fac_check=$(git grep Log -- $FILE)
    -   if [[ -n ${log_fac_check} ]]; then
    -     echo -e "\e[31;43m デバッグコードが残っている可能性があります。'\n'削除してください \e[m"
    -     IS_LOG_REMAIN_ERROR=1
    -   else
    -     IS_LOG_REMAIN_ERROR=0
    -   fi
    - done
    - if [ $SYNTAX_CHECK -eq 0 -a $IS_ERROR -eq 0 -a $IS_ERROR_LOG_REMAIN_ERROR -eq 0 -a $IS_LOG_REMAIN_ERROR -eq 0 ]; then
    - exit 0
    - else
    - echo -e "\e[31;43m 修正を行った上で再度コミットしてください \e[m"
    - exit 1
    - fi
  except:
    - feature/cimx-seat
    
deploy_production:
  stage: deploy
  script:
    - git pull origin feature/cimx-seat
    - composer global require laravel/envoy
    - ~/.composer/vendor/bin/envoy run deploy
  only:
    - feature/cimx-seat

    
